version: '3'
services:
  webapp:
    build: .
    ports:
      - "8080:80"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp_db
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_db

  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webapp_db
    ports:
      - "3306:3306"
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
